services:
  nginx:
    image: hybula/lookingglass-nginx:1
    container_name: lg-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: unless-stopped
    depends_on:
      - php-fpm
    networks:
      - lookingglass

  php-fpm:
    image: hybula/lookingglass-php:1
    container_name: lg-php
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    restart: unless-stopped
    networks:
      - lookingglass
    environment:
      LOCATION: Doetinchem
      FACILITY: InterDC
      FACILITY_URL: https://www.peeringdb.com/net/33444
      LOGO_URL: https://ck-itsolutions.nl/
      LOGO: '<img src="https://images.ck-itsolutions.nl/ckitsolutions/logo-light.svg" alt="CK IT Solutions" style="height: 60px; width: auto;">'
      LOGO_DARK: '<img src="https://images.ck-itsolutions.nl/ckitsolutions/logo-dark.svg" alt="CK IT Solutions" style="height: 60px; width: auto;">'
      IPV4_ADDRESS: 146.103.47.1
      IPV6_ADDRESS: 2a05:dfc1:5503::1
      MAPS_QUERY: Doetinchem

      # Pass these variables with any arbitrary value to disable the respective block.
      # DISABLE_BLOCK_NETWORK: 'true'
      # DISABLE_BLOCK_LOOKINGGLASS: 'true'
      # DISABLE_BLOCK_SPEEDTEST: 'true'
      # Uncomment to enable the custom block, which you can use to add something custom to the LG.
      # ENABLE_CUSTOM_BLOCK: 'true'
      # Uncomment if you require visitors to accept the Terms of Use; the value should be a link to the terms.
      # LG_TERMS: http://localhost/

  # iperf3:
  #   image: networkstatic/iperf3:latest
  #   container_name: lg-iperf3
  #   network_mode: host
  #   command: -s
  #   tty: true
  #   stdin_open: true
  #   restart: unless-stopped

networks:
  lookingglass:
    driver: bridge
